### ISSUE TITLE
Mesh generation breaks when sprites size is scaled down using the MaxSize texture import setting

### ISSUE THREAD

**Issue by MateuszRe** [sr4dev/Unity-SpriteAssist#37]
Thanks for an amazing tool! I noticed an issue that happens when i try to scale down the size of the texture with the unity MaxSize import setting, example (left is native size, right is scaled down):
![SpriteAssist](https://user-images.githubusercontent.com/98807023/160182813-8f502487-f181-4e48-852e-564a4d83711a.png)

**Comment by sr4dev** [comment]
Thank you for youre report!
I fixed it.

https://github.com/sr4dev/Unity-SpriteAssist/releases/tag/v0.12.7
