### ISSUE TITLE
Preview windows on wide or tall sprites

### ISSUE THREAD

**Issue by Gasparfx** [sr4dev/Unity-SpriteAssist#52]
Hi!
I have a bug with preview window on very wide or tall sprites. It only reproduces when preview window is small enough(I think that windows size should be smaller than sprite dimension).
Here are some screenshots:
Good:
![image](https://user-images.githubusercontent.com/3947711/214509000-f9d6fb57-7972-4e66-b142-4360067fcfdc.png)

Bad:
![image](https://user-images.githubusercontent.com/3947711/214509072-1075f070-9984-4db9-b346-75f229deaf05.png)

Image to reproduce:
[Example.zip](https://github.com/sr4dev/Unity-SpriteAssist/files/10497221/Example.zip)

My Unity version is 2022.2.3f1, but i think it can be reproduced on any 2022.2 Unity.

**Comment by sr4dev** [comment]
![image](https://user-images.githubusercontent.com/9159336/214512227-c9298ef1-d39e-41aa-beef-0947c8ff5a81.png)
Sprite Assist doesn't change the preview image. It's a Unity bug.
I reproduced this bug without Sprite Assist.

**Comment by Gasparfx** [comment]
Thank you for the reply. Looks like we need to report this to Unity)

**Comment by sr4dev** [comment]
@Gasparfx I have also received reports of this bug from other users, and it appears to be a reoccurrence of a bug that has happened in the past: https://issuetracker.unity3d.com/issues/sprite-preview-window-loses-pixels-and-the-sprites-are-indistinguishable-when-the-sprite-is-either-too-tall-or-too-wide

Unity doesn't seem to be aware of this situation, so I've opened a bug report and requested a fix.

**Comment by sr4dev** [comment]
My bug report is confirmed.

https://issuetracker.unity3d.com/issues/sprite-preview-is-broken-when-the-sprite-is-too-tall-or-too-wide

**Comment by sr4dev** [comment]
Fixed

https://issuetracker.unity3d.com/issues/sprite-preview-is-broken-when-the-sprite-is-too-tall-or-too-wide
