### ISSUE TITLE
Missing mode selector

### ISSUE THREAD

**Issue by stencg** [sr4dev/Unity-SpriteAssist#61]
Just installed the package by GIT link, no errors, but no mode selector in the inspector.
Unity 2022.3.8
Sprite Assist package 1.0.11
![Screenshot 2023-08-30 123956](https://github.com/sr4dev/Unity-SpriteAssist/assets/4937239/6af1b0b1-b0c5-4270-ab07-e4990f13c29f)

**Comment by stencg** [comment]
oh, should select included sprite, my bad

**Comment by sr4dev** [comment]
I am glad you noticed! Actually, I wanted to integrate it into Texture's Inspector, but the system didn't allow it, so I extending Sprite's Inspector.
