### ISSUE TITLE
Request Guide for creating shader/material compatible with this tool

### ISSUE THREAD

**Issue by lamlnt** [sr4dev/Unity-SpriteAssist#70]
Hi, I want to create a custom shader/material for this tool, more specifically one that will also take in a normal Map and a Mask Map to interact with lighting. 

1. Where can I change the Material/Shader (aside from manually assigning to the prefab)?
2. Is there anything I should notice when writing a custom shader for this tool? (maybe could you provide an example or a template?)

**Comment by sr4dev** [comment]
1. To change the Material/Shader, you need to either change the Material in the Mesh Renderer of the Mesh Prefab or click on the Material to change the Shader in use. If you want to change the default shader, you can also change the default shader in ProjectSettings -> SpriteAssist.
2. Using custom shaders is not a problem. However, there is a fundamental issue. In games that use lighting and shadows, problems may arise. I am using this tool to create my game. However, my game does not use lighting. Therefore, it has not been sufficiently tested for lighting. There is an issue (https://github.com/sr4dev/Unity-SpriteAssist/issues/38) where the normals of the meshes generated through SpriteAssist are incorrect, and this has not been fixed yet.
